QUIZ_DATA = [
    # 🔢 1. Matematika
    ("5 + 3 = ?", "8"),
    ("9 - 4 = ?", "5"),
    ("6 * 2 = ?", "12"),
    ("15 / 3 = ?", "5"),
    ("10 + 10 = ?", "20"),
    ("7 * 1 = ?", "7"),
    ("11 - 6 = ?", "5"),
    ("9 + 2 = ?", "11"),
    ("16 / 4 = ?", "4"),
    ("2 * 4 = ?", "8"),
    ("8 + 7 = ?", "15"),
    ("12 - 5 = ?", "7"),
    ("3 * 3 = ?", "9"),
    ("18 / 6 = ?", "3"),
    ("20 - 8 = ?", "12"),
    ("4 + 6 = ?", "10"),
    ("14 / 2 = ?", "7"),
    ("9 * 1 = ?", "9"),
    ("25 - 15 = ?", "10"),
    ("30 / 5 = ?", "6"),
    ("5 * 5 = ?", "25"),
    ("13 + 6 = ?", "19"),
    ("21 - 9 = ?", "12"),
    ("8 * 3 = ?", "24"),
    ("36 / 6 = ?", "6"),
    ("7 + 8 = ?", "15"),
    ("10 - 7 = ?", "3"),
    ("6 * 6 = ?", "36"),
    ("45 / 5 = ?", "9"),
    ("18 - 3 = ?", "15"),
    ("11 + 11 = ?", "22"),
    ("8 * 2 = ?", "16"),
    ("27 / 3 = ?", "9"),
    ("19 - 14 = ?", "5"),
    ("3 + 4 = ?", "7"),
    ("10 * 2 = ?", "20"),
    ("24 / 4 = ?", "6"),
    ("32 - 12 = ?", "20"),
    ("6 + 9 = ?", "15"),
    ("7 * 2 = ?", "14"),
    ("12 / 3 = ?", "4"),
    ("9 + 5 = ?", "14"),
    ("13 - 6 = ?", "7"),
    ("8 * 1 = ?", "8"),
    ("40 / 8 = ?", "5"),
    ("14 + 7 = ?", "21"),
    ("15 - 9 = ?", "6"),
    ("9 * 3 = ?", "27"),
    ("50 / 5 = ?", "10"),
    ("6 + 6 = ?", "12"),

    # 🍏 2. Emoji savollar
    ("Ushbu mevani yozing: 🍎", "Olma"),
    ("Bu meva nima: 🍌", "Banan"),
    ("Bu hayvon: 🐶", "It"),
    ("Bu meva: 🍇", "Uzum"),
    ("Bu ob-havo belgisi: ☀️", "Quyosh"),
    ("Bu qanday ichimlik: ☕", "Choy"),
    ("Bu transport vositasi: 🚗", "Mashina"),
    ("Bu qaysi sport turi: ⚽", "Futbol"),
    ("Bu davlat bayrog‘i: 🇺🇿", "O‘zbekiston"),
    ("Bu meva: 🍓", "Qulupnay"),
    ("Bu meva: 🍍", "Ananas"),
    ("Bu hayvon: 🐱", "Mushuk"),
    ("Bu hayvon: 🐰", "Quyon"),
    ("Bu ob-havo: 🌧️", "Yomg‘ir"),
    ("Bu transport: 🚲", "Velosiped"),
    ("Bu sport turi: 🏀", "Basketbol"),
    ("Bu meva: 🍒", "Gilos"),
    ("Bu bayroq: 🇺🇸", "Amerika"),
    ("Bu hayvon: 🐮", "Sigir"),
    ("Bu meva: 🍑", "Shaftoli"),
    ("Bu hayvon: 🐸", "Qurbaqa"),
    ("Bu ob-havo: ❄️", "Qor"),
    ("Bu ichimlik: 🥛", "Sut"),
    ("Bu transport: 🚕", "Taksi"),
    ("Bu hayvon: 🦁", "Sher"),
    ("Bu meva: 🍋", "Limon"),
    ("Bu hayvon: 🐔", "Tovuq"),
    ("Bu sport turi: 🏸", "Badminton"),
    ("Bu transport: ✈️", "Samolyot"),
    ("Bu meva: 開", "Kivi"), 
    ("Bu hayvon: 🐷", "Cho‘chqa"),
    ("Bu ob-havo: 🌥️", "Bulutli"),
    ("Bu ichimlik: 🍹", "Kokteyl"),
    ("Bu sport: 🥊", "Boks"),
    ("Bu meva: 🍊", "Apelsin"),
    ("Bu bayroq: 🇷🇺", "Rossiya"),
    ("Bu hayvon: 🐵", "Maymun"),
    ("Bu meva: 🍈", "Qovun"),
    ("Bu hayvon: 🐢", "Toshbaqa"),
    ("Bu transport: 🚤", "Qayiq"),
    ("Bu sport turi: 🏐", "Voleybol"),
    ("Bu ob-havo: 🌈", "Kamalak"),
    ("Bu ichimlik: 🧃", "Sok"),
    ("Bu meva: 🥭", "Mango"),
    ("Bu bayroq: 🇹🇷", "Turkiya"),
]
